Repository SSUMC-7th/Web_B, pull requests merged in 2024-10, with the labels that each got.

#12 [week3/mission] 영화페이지 구현
  WEEK3/.gitignore
  WEEK3/.prettierrc
  WEEK3/README.md
  WEEK3/eslint.config.js
  WEEK3/index.html
  WEEK3/package.json
  WEEK3/public/vite.svg
  WEEK3/src/App.jsx
  WEEK3/src/api/MovieList.jsx
  WEEK3/src/assets/fighting.jpg
  WEEK3/src/assets/happy.png
  WEEK3/src/assets/monday.jpg
  WEEK3/src/assets/react.svg
  WEEK3/src/assets/time.jpg
  WEEK3/src/components/Navbar.jsx
  WEEK3/src/components/Not-found.jsx
  WEEK3/src/components/Sidebar.jsx
  WEEK3/src/main.jsx
  WEEK3/src/outlet/root-layout.jsx
  WEEK3/src/pages/Home.jsx
  WEEK3/src/pages/Join.jsx
  WEEK3/src/pages/Login.jsx
  WEEK3/src/pages/Movies.jsx
  WEEK3/src/pages/Search.jsx
  WEEK3/src/routers/router.jsx
  WEEK3/src/styles/GlobalStyle.jsx
  WEEK3/vite.config.js
  WEEK3/yarn.lock
Labels: Ch 3

#11 [week3/mission] Movie Page 구현
  week3/.gitignore
  week3/README.md
  week3/eslint.config.js
  week3/index.html
  week3/package.json
  week3/public/vite.svg
  week3/src/App.css
  week3/src/App.jsx
  week3/src/assets/images/category1.webp
  week3/src/assets/images/category2.webp
  week3/src/assets/images/category3.webp
  week3/src/assets/images/category4.webp
  week3/src/assets/react.svg
  week3/src/components/MovieItem.jsx
  week3/src/components/MovieList.jsx
  week3/src/components/navbar.jsx
  week3/src/components/sidebar.jsx
  week3/src/index.css
  week3/src/layout/root-layout.jsx
  week3/src/main.jsx
  week3/src/mocks/movies.js
  week3/src/pages/categories.jsx
  week3/src/pages/home.jsx
  week3/src/pages/login.jsx
  week3/src/pages/movies.jsx
  week3/src/pages/not-found.jsx
  week3/src/pages/search.jsx
  week3/src/pages/signup.jsx
  week3/vite.config.js
  week3/yarn.lock
Labels: Ch 3

#13 [week3/mission] 영화 사이트 제작
  .DS_Store
  01/package.json
  01/postcss.config.js
  01/src/App.css
  01/src/App.jsx
  01/src/components/Lists.jsx
  01/src/components/Search.jsx
  01/src/index.css
  01/tailwind.config.js
  03/movie-3week/.gitignore
  03/movie-3week/README.md
  03/movie-3week/eslint.config.js
  03/movie-3week/index.html
  03/movie-3week/package-lock.json
  03/movie-3week/package.json
  03/movie-3week/public/vite.svg
  03/movie-3week/src/App.css
  03/movie-3week/src/App.jsx
  03/movie-3week/src/assets/images/category1.jpg
  03/movie-3week/src/assets/images/category2.jpg
  03/movie-3week/src/assets/images/category3.jpg
  03/movie-3week/src/assets/images/category4.jpg
  03/movie-3week/src/assets/react.svg
  03/movie-3week/src/category/nowplaying.jsx
  03/movie-3week/src/category/pupular.jsx
  03/movie-3week/src/category/toprated.jsx
  03/movie-3week/src/category/upcoming.jsx
  03/movie-3week/src/components/navbar.jsx
  03/movie-3week/src/components/sidebar.jsx
  03/movie-3week/src/index.css
  03/movie-3week/src/layout/root-layout.jsx
  03/movie-3week/src/main.jsx
  03/movie-3week/src/pages/category.jsx
  03/movie-3week/src/pages/home.jsx
  03/movie-3week/src/pages/login.jsx
  03/movie-3week/src/pages/movies.jsx
  03/movie-3week/src/pages/not-found.jsx
  03/movie-3week/src/pages/search.jsx
  03/movie-3week/src/pages/signin.jsx
  03/movie-3week/vite.config.js
Labels: Ch 3

#8 [week2/mission] ToDo List (React) 구현
  02/umc_02/.gitignore
  02/umc_02/README.md
  02/umc_02/eslint.config.js
  02/umc_02/index.html
  02/umc_02/package-lock.json
  02/umc_02/package.json
  02/umc_02/public/vite.svg
  02/umc_02/src/App.css
  02/umc_02/src/App.jsx
  02/umc_02/src/assets/react.svg
  02/umc_02/src/components/Form.css
  02/umc_02/src/components/Form.jsx
  02/umc_02/src/components/List.css
  02/umc_02/src/components/List.jsx
  02/umc_02/src/index.css
  02/umc_02/src/main.jsx
  02/umc_02/vite.config.js
  02/umc_02_2/.gitignore
  02/umc_02_2/README.md
  02/umc_02_2/eslint.config.js
  02/umc_02_2/index.html
  02/umc_02_2/package-lock.json
  02/umc_02_2/package.json
  02/umc_02_2/public/vite.svg
  02/umc_02_2/src/App.css
  02/umc_02_2/src/App.jsx
  02/umc_02_2/src/assets/react.svg
  02/umc_02_2/src/index.css
  02/umc_02_2/src/main.jsx
  02/umc_02_2/src/mocks/movies.js
  02/umc_02_2/vite.config.js
Labels: Ch 2

#16 [week4/mission] 영화 상세 페이지 제작
  week4/.gitignore
  week4/README.md
  week4/eslint.config.js
  week4/index.html
  week4/package.json
  week4/public/vite.svg
  week4/src/App.css
  week4/src/App.jsx
  week4/src/apis/axios-instance.js
  week4/src/assets/images/category1.webp
  week4/src/assets/images/category2.webp
  week4/src/assets/images/category3.webp
  week4/src/assets/images/category4.webp
  week4/src/assets/react.svg
  week4/src/components/MovieDetailInfo.jsx
  week4/src/components/MovieDetailPeople.jsx
  week4/src/components/MovieItem.jsx
  week4/src/components/MovieList.jsx
  week4/src/components/navbar.jsx
  week4/src/components/sidebar.jsx
  week4/src/hooks/useCustomFetch.js
  week4/src/index.css
  week4/src/layout/root-layout.jsx
  week4/src/main.jsx
  week4/src/mocks/movies.js
  week4/src/pages/categories.jsx
  week4/src/pages/home.jsx
  week4/src/pages/login.jsx
  week4/src/pages/movieDetail.jsx
  week4/src/pages/movies.jsx
  week4/src/pages/not-found.jsx
  week4/src/pages/nowPlaying.jsx
  week4/src/pages/popular.jsx
  week4/src/pages/search.jsx
  week4/src/pages/signup.jsx
  week4/src/pages/topRated.jsx
  week4/src/pages/upComing.jsx
  week4/src/styles/globalstyles.jsx
  week4/vite.config.js
  week4/yarn.lock
Labels: Ch 4
